### ISSUE TITLE
Forge 1.20.1 Release

### ISSUE THREAD

**Issue by metl-play** [lazul1ne/XXLPackets#2]
Hello, I see there is a Forge 1.20.x branch in the source and I want to kindly ask for an upload of this version on Modrinth if possible.

**Comment by metl-play** [comment]
I just see last edit was 19 Days ago. Is this version not ready yet?

**Comment by lazul1ne** [comment]
> I just see last edit was 19 Days ago. Is this version not ready yet?

Hi, sorry for the delay in my response, but yes. If I remember correctly the forge 1.20.x version did not work which is why I did not upload it already.

**Comment by lazul1ne** [comment]
https://modrinth.com/mod/xxl-packets/version/1.05-1.20.1-forge

Will remove old forge branches sometime in the near future.
